[package]
name = "walksnail-osd-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.3"
egui = "0.21.0"
egui_extras = { version = "0.21.0", features = ["image"] }
# ffmpeg-sidecar = "0.2.0"
ffmpeg-sidecar = { git = "https://github.com/nathanbabcock/ffmpeg-sidecar" }
ffprobe = "0.3.3"
image = "0.24.5"
indoc = "2.0.0"
itertools = "0.10.5"
rayon = "1.6.1"
rfd = "0.11.1"
thiserror = "1.0.38"

# Use local version of eguis and friends
# eframe = { path = "../egui/crates/eframe" }
# egui = { path = "../egui/crates/egui" }
# egui_extras = { path = "../egui/crates/egui_extras", features = ["image"] }