[env]
FFMPEG_INCLUDE_DIR = { value = "ffmpeg-5.1-windows-desktop-vs2022-gpl-lite/include", relative = true}
FFMPEG_LIB_DIR = { value = "ffmpeg-5.1-windows-desktop-vs2022-gpl-lite/lib", relative = true}
