name: Release

on:
  push:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        targets:
          [
            {
              os: windows-latest,
              target: x86_64-pc-windows-msvc,
              name: windows64,
              ffmpeg_url: "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z",
            },
          ]
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: Cache dependencies
        id: extcache
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/ext/"

      - name: Install cargo-binstall
        if: ${{ matrix.targets.os == 'windows-latest' }}
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Install cargo-wix
        if: ${{ matrix.targets.os == 'windows-latest' }}
        run: cargo binstall cargo-wix --no-confirm

      - name: Build
        run: cargo build --release

      - name: Download ffmpeg
        if: ${{ matrix.targets.os == 'windows-latest' && steps.extcache.outputs.cache-hit != 'true' }}
        run: |
          mkdir ${{ github.workspace }}/ext/ffmpeg
          cd ${{ github.workspace }}}/ext/ffmpeg
          curl -L ${{ matrix.targets.ffmpeg_url }} -o ffmpeg.zip
          7z e ffmpeg.zip

      - name: Create Windows installer
        if: ${{ matrix.targets.os == 'windows-latest'}}
        continue-on-error: true
        run: |
          cargo wix --include resources\release\wix\main.wxs --nocapture --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.targets.name }}
          path: ${{ github.workspace }}/target/wix/walksnail-osd-tool-*.msi
